### PR TITLE
adding from io and operator imports

### PR DESCRIPTION
**Pull request by cowboyuniverse**

### CODE REVIEW

**Comment by cowboyuniverse** [comment]
my test cases failed because i've taken out these lines on top of my project.  placed them back into it just now and all checks have passed :)

from io import open
from operator import itemgetter

**Comment by rcliao** [comment]
Python naming convention is `under_score_case` not `lowerCaelCase`

See https://www.python.org/dev/peps/pep-0008/

**Comment by rcliao** [comment]
On these lines: https://github.com/csula-students/cs4660-fall-2017-cowboyuniverse/blob/0ba2cbeb234074fceec2d90709b3c584b42aad31/cs4660/graph/graph.py#L26-L33

You shouldn't check for the graph type to add the value to graph internal data structure directly. That is a leaky implementation. The graph internal data structure (e.g. two dimensional array) shouldn't be known by outside world. Instead, you should call `add_edge` method to add edge accordingly. Then, in the `add_edge` method, you can do specific logic accordingly.

**Comment by rcliao** [comment]
https://github.com/csula-students/cs4660-fall-2017-cowboyuniverse/blob/0ba2cbeb234074fceec2d90709b3c584b42aad31/cs4660/graph/graph.py#L146-L152

This should be O(n)

**Comment by rcliao** [comment]
https://github.com/csula-students/cs4660-fall-2017-cowboyuniverse/blob/0ba2cbeb234074fceec2d90709b3c584b42aad31/cs4660/graph/graph.py#L154-L162

O(n)

**Comment by rcliao** [comment]
https://github.com/csula-students/cs4660-fall-2017-cowboyuniverse/blob/0ba2cbeb234074fceec2d90709b3c584b42aad31/cs4660/graph/graph.py#L168-L170

When removing the node from AdjacencyMatrix, you are supposed to resize the matrix (e.g. removing the corresponding rows and columns)

**Comment by rcliao** [comment]
https://github.com/csula-students/cs4660-fall-2017-cowboyuniverse/blob/0ba2cbeb234074fceec2d90709b3c584b42aad31/cs4660/graph/graph.py#L131-L134

Good changes of the nodes to dictionary for faster retrieval of index value.

**Pull request merged**
